# Generated by Django 5.2 on 2025-12-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
    ]
