# Generated by Django 5.2 on 2025-12-24 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_student_division'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marks',
            options={'ordering': ['student__enrollment_no', 'subject__code']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['enrollment_no']},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_number',
        ),
    ]
