# Generated by Django 5.2 on 2025-12-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0004_alter_marks_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mentor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
