# Generated by Django 5.2 on 2026-02-11 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0005_student_mentor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_session', models.CharField(max_length=50)),
                ('seat_no', models.CharField(blank=True, max_length=30)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('spi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cpi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('earned_credits', models.IntegerField(blank=True, null=True)),
                ('earned_grade_points', models.IntegerField(blank=True, null=True)),
                ('total_credits', models.IntegerField(blank=True, null=True)),
                ('total_grade_points', models.IntegerField(blank=True, null=True)),
                ('result_status', models.CharField(default='PASS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_sheets', to='allocation.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'semester', 'exam_session')},
            },
        ),
        migrations.CreateModel(
            name='ResultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=200)),
                ('course_credit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(max_length=5)),
                ('result_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='allocation.resultsheet')),
            ],
            options={
                'ordering': ['course_code'],
            },
        ),
    ]
