# Generated by Django 5.2 on 2026-02-12 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0006_resultsheet_resultentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='external_max',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='internal_max',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='max_marks',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
