# Generated by Django 5.2 on 2026-02-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0007_remove_subject_marks_and_marks_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
