# Generated by Django 5.2 on 2026-02-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0008_add_subject_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='elective_group',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
