# Generated by Django 5.2 on 2026-02-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0010_faculty_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='division',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I')], default='A', max_length=2),
        ),
    ]
