# Generated by Django 5.2 on 2026-02-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0011_alter_student_division'),
        ('allocation', '0011_remove_seat_no_fields'),
    ]

    operations = [
    ]
