# Generated by Django 5.2 on 2026-02-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0016_alter_student_division_noticeattachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BonafideCertificateIssue',
        ),
    ]
