# Generated by Django 5.2 on 2026-03-11 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0018_student_admission_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('MID', 'Mid Semester'), ('FINAL', 'Final Exam')], max_length=10)),
                ('exam_session', models.CharField(max_length=50)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('pass_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allocation.faculty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_records', to='allocation.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_records', to='allocation.subject')),
            ],
            options={
                'ordering': ['-updated_at', 'student__enrollment_no'],
                'unique_together': {('student', 'subject', 'exam_type', 'exam_session', 'attempt_no')},
            },
        ),
    ]
