# Generated by Django 5.2 on 2026-03-13 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0019_studentmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='target_scope',
            field=models.CharField(choices=[('ALL', 'All Students'), ('SEMESTER', 'Specific Semester'), ('DIVISION', 'Specific Division'), ('FAILING', 'Students With Fail Records'), ('LOW_ATTENDANCE', 'Students Below Attendance Threshold')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='MarksAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('MID', 'Mid Semester'), ('FINAL', 'Final Exam')], max_length=10)),
                ('exam_session', models.CharField(max_length=50)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('old_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('new_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('old_absent', models.BooleanField(default=False)),
                ('new_absent', models.BooleanField(default=False)),
                ('old_max_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('new_max_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('old_pass_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('new_pass_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('action', models.CharField(choices=[('UPDATE', 'Update'), ('FREEZE', 'Freeze'), ('UNFREEZE', 'Unfreeze')], default='UPDATE', max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.student')),
                ('student_mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='allocation.studentmark')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.subject')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('MEETING', 'Counselling Meeting'), ('CALL', 'Parent Call'), ('REMEDIAL', 'Remedial Assigned'), ('WARNING', 'Warning Given'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_actions', to='allocation.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarksFreezeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('MID', 'Mid Semester'), ('FINAL', 'Final Exam')], max_length=10)),
                ('exam_session', models.CharField(max_length=50)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('is_frozen', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('frozen_at', models.DateTimeField(auto_now=True)),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.subject')),
            ],
            options={
                'ordering': ['-frozen_at'],
                'unique_together': {('semester', 'subject', 'exam_type', 'exam_session', 'attempt_no')},
            },
        ),
    ]
