# Generated by Django 5.2 on 2026-03-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0020_notice_target_scope_notice_target_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='target_scope',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='target_value',
        ),
    ]
