# Generated by Django 5.2 on 2026-03-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0022_mentorassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentorassignment',
            unique_together={('faculty', 'semester', 'division')},
        ),
    ]
